### ISSUE TITLE
Error in GTSAM

### ISSUE THREAD

**Issue by HappyB1rthday** [lukasvst/dm-vio#11]
Error:<gtsam/base/DerivedValue.h> no such file or directory. 
The GTSAM code I got from github don't have such a file. Is that a GTSAM version error?

**Comment by lukasvst** [comment]
Yes, originally only commit `a738529af9754c7a085903f90ae8559bbaa82e75` of GTSAM was supported.
I have just updated the master branch however so now it should work to run `git pull` in the DM-VIO folder and then rebuild.
