### ISSUE TITLE
live saving pictures get 

### ISSUE THREAD

**Issue by Zoltan3057** [lukasvst/dm-vio#17]
Hi,
It seems saved images sometimes have misalignment. Using cv::Mat clone() may improve this condition.

![Screenshot from 2022-06-24 15-54-42](https://user-images.githubusercontent.com/37650678/175490509-f552f388-8fa7-48ab-b4a9-6873121bafb2.png)

```
void dmvio::DatasetSaver::addImage(cv::Mat& mat, double timestamp, double exposure)
{
    {
        std::unique_lock<std::mutex> lock(mutex);
        imageQueue.emplace_back(mat.clone(), timestamp, exposure);
    }
    frameArrivedCond.notify_all();
}
```

**Comment by lukasvst** [comment]
Thanks a lot for reporting this and providing a solution! 
It should be fixed now, but please let me know if the problem still arises.
