### ISSUE TITLE
If we can work well when visual info is not good at a short time

### ISSUE THREAD

**Issue by yushijie94** [lukasvst/dm-vio#23]
I want to know, if I go into a black house, so I can not get any visual info. Can It still work by using IMU info at a short time and when I get out the black house, I can get the true trajectory showing I was in and out.
Thanks!

**Comment by lukasvst** [comment]
It depends on how little visual information there is and on the time.
When there is absolutely no visual information, only the IMU can be used for pose estimation and this will drift very quickly (few seconds). Note, that this is a pure odometry system, so it will usually not correct the trajectory after regaining vision.

But if you still have some visual information, or loose it only for a short period of time, the system should work.

**Comment by yushijie94** [comment]
> It depends on how little visual information there is and on the time. When there is absolutely no visual information, only the IMU can be used for pose estimation and this will drift very quickly (few seconds). Note, that this is a pure odometry system, so it will usually not correct the trajectory after regaining vision.
> 
> But if you still have some visual information, or loose it only for a short period of time, the system should work.

OK, If I test in real data, I will try to verify the conclusion. Thanks for you reply!

**Comment by Leerw** [comment]
@yushijie94 hi, are there any conclusions?
