### ISSUE TITLE
Does DM-VIO have the function of saving and loading maps and positioning in existing maps？

### ISSUE THREAD

**Issue by JACKLiuDay** [lukasvst/dm-vio#25]
Hi, thank you for your great work about DM-VIO. I have a project for my robot. And I need to localize the robot in my campus. I think the localization will be more stable if we have a pre built map and we just need to localize in the map. So, dose dm-vio support this function?

**Comment by lukasvst** [comment]
Currently, DM-VIO is a pure odometry system, meaning that it does not perform loop-closure nor can it load a prebuilt map.
