### ISSUE TITLE
Compilation error: Missing gtsam/base/DerivedValue.h

### ISSUE THREAD

**Issue by GarronLiu** [lukasvst/dm-vio#3]
Firstly, thank you for your contributions! Aimed to fix the problem as shown in the title, I have checked Gtsam file, but got nothing about DerivedValue.h. Could you  give any hints about this? Thank you very much！
![2022-03-31 15-00-41屏幕截图](https://user-images.githubusercontent.com/78224483/160996777-0dd2d9ab-e549-4144-a586-61e0dd0f76a0.png)

**Comment by lukasvst** [comment]
Thanks for checking out the code!
At the moment the newest GTSAM version is not supported yet.
Can you go to the directory where you downloaded GTSAM and run
`git checkout a738529af9754c7a085903f90ae8559bbaa82e75`
and rebuild everything afterwards?

At a later point I will probably upgrade the project to the newest version of GTSAM.

**Comment by GarronLiu** [comment]
> Thanks for checking out the code! At the moment the newest GTSAM version is not supported yet. Can you go to the directory where you downloaded GTSAM and run `git checkout a738529af9754c7a085903f90ae8559bbaa82e75` and rebuild everything afterwards?
> 
> At a later point I will probably upgrade the project to the newest version of GTSAM.

After following your suggestion, the compilation has been successfully done! Thank you again!
