### ISSUE TITLE
What is gtFile ? And what is the different between gtFile and imuFile?

### ISSUE THREAD

**Issue by HongShaojiang** [lukasvst/dm-vio#4]
Hi, I want to run dm-vio on my dataset with imu, and I got Aborted(core dumped), I dont know the different between gtFile and imuFile, could you explain this two file. Tks.

**Comment by hellovuong** [comment]
gtFile is the ground trutth for your datasets, usually the poses from motion capture, or other reliable SLAM, etc. imuFile is simply the imu datafile.

**Comment by HongShaojiang** [comment]
Thank you very much!
