### ISSUE TITLE
The TUM-VI Euroc is not available

### ISSUE THREAD

**Issue by DZXL** [lukasvst/dm-vio#52]
In the 3rd step Running, we need to "Download a TUM-VI sequence (download in the format Euroc / DSO 512x512) at https://vision.in.tum.de/data/datasets/visual-inertial-dataset". However, when I open the URL, it shows that the URL is not available. Is there any other way I can download this dataset?

**Comment by endlesmoon** [comment]
hi,Have you successfully run the tum-vi dataset?
