### ISSUE TITLE
Will dm-vio work with low sub 10Hz IMU sample rate?

### ISSUE THREAD

**Issue by finickyDrone** [lukasvst/dm-vio#55]
Hello, we're trialing new methods for performing real-time SLAM off-board on a monocular nano UAV (30g). The main problem is we can only get IMU data at around 8 Hz, where as generally when running on-board you get 200Hz. Do you believe it is possible to  get somewhat good results using dm-vio on such low IMU frequency? I was thinking maybe we'd just slow down the UAV, but wanted to get your sense as to whether this is possible at all with dm-vio, or we should just try something else.

Really appreciate all your hard work and making code available. Thanks!

**Comment by lukasvst** [comment]
You can try it out, but I would not expect it to work well in this use-case. As you wrote yourself IMU data usually comes at a higher frequency than camera data.
Another thing to consider is the time-synchronization, i.e. how accurate your IMU data is timestamped with respect to the camera. The system generally expects this to be very accurate. 

If you try it out nevertheless, you might want consider increasing the IMU noise parameters to reflect that the IMU gives you less reliable information than normal.

**Comment by finickyDrone** [comment]
Thanks for the feedback Lukas. Really appreciate it :)
