### ISSUE TITLE
Any plans to release a version that supports ros?

### ISSUE THREAD

**Issue by Taeyoung96** [lukasvst/dm-vio#9]
@lukasvst  
Hi, Thanks for your great work!  
I have a question about DM-VIO support ROS.  
Do you have any plans to support the ros version?  
Thanks,

**Comment by lukasvst** [comment]
It depends on how large the interest in ROS support is and in how much time I will have.
The first plan is to add a live demo (without ROS) for some Realsense cameras, which could be extended to a ROS driver afterwards.

Maybe people who are interested in ROS-support could mark the post with 👍 so I get an overview?

**Comment by lukasvst** [comment]
Maybe a small update on this. The live demo for the Realsense T265 is working and the code for this will be published in the next 2-3 weeks. I will also release a ROS driver soon, hopefully next month (June).

**Comment by Taeyoung96** [comment]
@lukasvst   
Thank you so much for not forgetting to reply.  
Looking forward to some great code!  :laughing:

**Comment by lukasvst** [comment]
The live version for the Realsense T265 is now public, for more information (including some general tips for running on custom datasets) see https://github.com/lukasvst/dm-vio/blob/master/doc/RealsenseLiveVersion.md

The plan is still to release a ROS driver based on this live version towards the end of this month.

**Comment by lukasvst** [comment]
The ROS wrapper is now released at https://github.com/lukasvst/dm-vio-ros
I hope it will be useful!
